### PR TITLE
build(kodiak): add Kodiak configuration

### LINKED ISSUE #822: Set up and configure Kodiak integration
https://kodiakhq.com/#quickstart

### PR DESCRIPTION
**Pull request by SimonFinney**
## Affected issue

Resolves #822 

## Proposed change

Add basic Kodiak configuration to manage merging and updating of  approved PRs

### CODE REVIEW

**Review by j1mie — COMMENTED** [review]
Do you have to install kodiak as a dependency, too?

**Comment by SimonFinney** [comment]
@j1mie Good question! According to @joshblack , it's pre-configured in the `carbon-design-system` org so all we need to do is provide a configuration file

**Review by j1mie — APPROVED** [review]
Awesome... Approved!

**Pull request merged**
