### PR TITLE
fix(tag-wall-filter): fix input positioning

### LINKED ISSUE #702: Make Tag wall filter Search bar  fixed on top
## Request 
Fix Search bar on top

- **Short description -**

The search bar currently disappear when user scrolls down the list of options. It would help the users if the search bar was always visible for easy access. 
 

### Details
https://ibm-security.carbondesignsystem.com/?path=/story/patterns-tagwallfilter--tagwall-with-filter-list-for-multiselect
- **Application / team -** TII
- **Work item -**  -[]()
- **Needed by -** TII 

### Proposal
Make Tag wall filter search bar stay on top

### PR DESCRIPTION
**Pull request by SimonFinney**
## Affected issue

Resolves #702

## Proposed changes

- Fix `TagWallFilter` input positioning
- Refactor imports

### CODE REVIEW

**Comment by petervachon** [comment]
Looking good! Is there a way to introduce the gradient under the search input on scroll? We have the gradient at the bottom of the tearsheet indicating that there is additional content, I'm wondering if we should include the same effect at the top?

**Comment by SimonFinney** [comment]
Good catch!

**Comment by SimonFinney** [comment]
Thanks @petervachon - I've made the changes suggested, let me know your thoughts 🎉

**Pull request merged**
