### PR TITLE
feat(carbon): upgrade to `v10.15`

### LINKED ISSUE #613: fix: pagination component, forward button rendered in black instead of white
## Bug - 
Pagination svg buttons are appearing in black instead of white in theme $carbon--theme--g10
**Expected behavior -**
Expect svg pagination buttons to be rendered in white.

**Actual behavior -**
Svg pagination buttons are being rendered in black.

### Screenshots
pagination-white_buttons
pagination-black buttons

### Affected browsers
All browsers

### Optional information

Example markup is attached.  For pagination black buttons removing fill="currentColor changes the colour of the svg to white

[PaginationMarkup.txt](https://github.com/carbon-design-system/ibm-security/files/4779495/PaginationMarkup.txt)

### PR DESCRIPTION
**Pull request by SimonFinney**
## Affected issue

Resolves #613

## Proposed changes

- Upgrade Carbon packages to `v10.15`
- Fix height issue with `FilterPanelAccordionItem`
- Add icon workaround for https://github.com/carbon-design-system/carbon/issues/5531#issuecomment-656028439
- Fix stories for `Tabs` and `TruncatedList`
- Update snapshots

### CODE REVIEW

**Comment by SimonFinney** [comment]
@jendowns / @petervachon I did a manual pass to verify and fix any noticeable issues, but this could use extra sets of eyes across the board

**Comment by petervachon** [comment]
Hi Simon, 

I'm going to list out some issues below. 

----

Screen Shot 2020-07-08 at 8 48 18 AM
Screen Shot 2020-07-08 at 8 52 38 AM

The selected state of the checkbox is being cut off. Summary card & filter

----

Screen Shot 2020-07-08 at 8 50 59 AM
The X icon is black, found in the search input

----

Screen Shot 2020-07-08 at 8 59 23 AM
Dropdown, when clicking on the drop-down the body of it becomes selected. 

----

Screen Shot 2020-07-08 at 9 08 53 AM
Ordered list line-height is tighter than what is in production 

Current line-height of the ordered list
Screen Shot 2020-07-08 at 9 09 05 AM

----

Screen Shot 2020-07-08 at 9 11 45 AM
Search with custom actions/buttons, the icons are reverse. 

----

Screen Shot 2020-07-08 at 9 13 13 AM
Tabs are horizontally scrollable

----

Screen Shot 2020-07-08 at 9 14 20 AM
Need to include padding for the time input

----

Screen Shot 2020-07-08 at 9 14 50 AM
When clicking the tooltip, it auto outlines the link

----

Screen Shot 2020-07-08 at 9 17 37 AM
The truncated list line-height is a bit tight. Production version below

Screen Shot 2020-07-08 at 9 17 43 AM

----

Screen Shot 2020-07-08 at 9 18 01 AM
Unordered list line-height is a bit tight. Production version below
Screen Shot 2020-07-08 at 9 18 03 AM

**Comment by jendowns** [comment]
@SimonFinney Is this ready to review again?

**Comment by SimonFinney** [comment]
@jendowns I haven't had a chance to revisit this in detail just yet, but everything bar the `Checkbox` and `TimePicker` issue have been addressed:

- For the `Checkbox`, it's unclear as of yet what a suitable fix would be on our end without modifying the base styles drastically
- The `TimePicker` issue exists in `dev` and an issue can be created to resolve it independently

**Pull request merged**
