### PR TITLE
feat(portal): add prop for overlay class

### PR DESCRIPTION
**Pull request by SimonFinney**
## Affected issue

Contributes to https://jsw.ibm.com/browse/SECCON-6926

## Proposed change

- Deprecate `onOverlayClick` in favour of `overlayOptions`
- Add option to supply class for overlay to `Portal`

### CODE REVIEW

**Review by codewood — APPROVED** [review]
No complaints from me. @JennChao, Henry should be able to use this to adjust z-indexs when we have multiple overlays.

**Review by dbrugger — APPROVED** [review]

**Review by JennChao — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
