### PR TITLE
fix(select): apply text-rendering style to stop safari from crashing

### LINKED ISSUE #149: Safari not responding (have to Force Quit) after paginator controls are clicked
## Bug - 
For https://ibm-security.carbondesignsystem.com/?path=/story/components-datatablepagination--pagination-data-table, when items per page selector or page selector are clicked **in Safari browser** there is no response, and user has to Force Quit to recover.  Chrome and Firefox do not have this issue.

**Expected behavior -**
Items per page selector opens and user can select the number of items:
image
Page selector opens and user can select the page:
image

**Actual behavior -**
The selectors do not open, Safari stops responding and user has to Force Quit to recover

### Steps for reproducing

1.  Open https://ibm-security.carbondesignsystem.com/?path=/story/components-datatablepagination--pagination-data-table in Safari browser
2.   Click the items per page selector
3.   Click the page selector
4.   Right click on the Safari icon to see that the application is not responding

### Screenshots
image

### Affected browsers
- [ Safari/605.1.15 on Mac OS X 10]

### PR DESCRIPTION
**Pull request by jendowns**
## Affected issues

- Resolves #149 

## Proposed changes

- resets the `text-rendering` style rule because `text-render: optimizeLegibility` appears to cause `select` elements in Safari to crash. See my comment here for webkit bug info & breakdown: https://github.com/carbon-design-system/ibm-security/issues/149#issuecomment-542298389

## Testing instructions

To see Safari breaking:
- Go to https://ibm-security.carbondesignsystem.com/?path=/story/components-select--default (or `Pagination`, which also uses a `Select` component that has an underlying `select` element) 
- Try interacting with the `Select` -- Safari will quickly "beach ball" and require a force quit.
- Force quit Safari

To see it fixed:
- Open the Netlify deployment for this PR (https://deploy-preview-157--ibm-security.netlify.com/) and view the `Select` component
- Try interacting with the `Select` component
- Note that you can open the `Select` options repeatedly, and Safari doesn't "beach ball" / require a force quit.

### CODE REVIEW

**Comment by jendowns** [comment]
@sharon-oboyle when you have a chance, do you mind taking a look at the testing instructions above (https://github.com/carbon-design-system/ibm-security/pull/157#issue-328367002) and seeing if you still see the issue identified in #149?

**Comment by sharon-oboyle** [comment]
@jendowns I followed the testing instructions above and the selector opens showing all the options. So the issue #149 where Safari stops responding is fixed, thanks.

However, I have been unable to select a different option on that selector.  I tried in Firefox and Safari.

**Comment by jendowns** [comment]
Hey @sharon-oboyle I can't replicate what you are referring to here. When I look at this PR deploy preview (https://deploy-preview-157--ibm-security.netlify.com) in Firefox and Safari, I am able to interact repeatedly with the `Select` component and the inner select in the `Pagination` component without issues. I can select new options as well. 🤔 Maybe you could post a video of what you are seeing?

**Comment by sharon-oboyle** [comment]
Hey @jendowns actually it seems to be happening in all browsers.  Here is a recording for Chrome.  As you see you can appear to select an option but the blue button text does not change to reflect the selected value.
[Screen Recording 2019-10-16 at 15.31.11.mov.zip](https://github.com/carbon-design-system/ibm-security/files/3734857/Screen.Recording.2019-10-16.at.15.31.11.mov.zip)

**Comment by sharon-oboyle** [comment]
Oh apologies, I just clicked on the link you gave originally and assumed that was the component you wanted me to test!  Yes I see now for the three components you have specified above that the fix is working in Safari and I can select any option.

**Comment by jendowns** [comment]
Awesome thank you @sharon-oboyle!

**Comment by sharon-oboyle** [comment]
Great job!  Thanks @jendowns!

**Pull request merged**
