### PR TITLE
refactor: remove Carbon style overrides

### PR DESCRIPTION
**Pull request by SimonFinney**
### Affected issue

Contributes to #973

### Proposed changes

This removes all Carbon style overrides to better align Security with core Carbon components.

### CODE REVIEW

**Comment by areddon** [comment]
This one would likely impact most consumers of the library with changes to margins and colors. Should we be making these preemptive migration changes in their own branch?

**Comment by SimonFinney** [comment]
> This one would likely impact most consumers of the library with changes to margins and colors. Should we be making these preemptive migration changes in their own branch?

Good catch! @dbrugger Maybe it's worth testing this one in the boilerplate?

**Review by cameroncalder — CHANGES_REQUESTED** [review]
I added all the noticed override discrepancies in this [Box Note](https://ibm.box.com/s/jfqbn9x969gqx3sixxe4he5xusfaorki)

**Comment by thekevinboyle** [comment]
Good to go

**Review by thekevinboyle — COMMENTED** [review]
good to go

**Pull request merged**
