### PR TITLE
fix(unstable): align experimental components with Carbon format

### PR DESCRIPTION
**Pull request by SimonFinney**
### Proposed changes

- Replace unstable `Pagination` with proxied Carbon variant
- Align experimental components with Carbon format

### CODE REVIEW

**Review by Deriohig — APPROVED** [review]
Just to confirm, there is a new unstable pagination component being proxied now? Will this change the underlying functionality or props of the deprecated unstable pagination component?

**Comment by SimonFinney** [comment]
@Deriohig Exactly! This will now reference Carbon's implementation per https://github.com/carbon-design-system/carbon/blob/main/packages/react/__tests__/__snapshots__/PublicAPI-test.js.snap#L7434-L7564 where the props match

**Pull request merged**
