### PR TITLE
Large and small tearsheet had odd scrolling behaviour in chrome versi…

### LINKED ISSUE #863: Bug: Chrome 87 —— Unexpected scrolling behaviour
### Description

Just creating a ticket to track a bug identified by @clairek20 [on Slack](https://ibm-security.slack.com/archives/CRV39QKP0/p1607523654128300) potentially related to Chrome 87.

---

Issues seen:
#### Large teasheet
We've seen odd behaviour in the [large tearsheet](https://ibm-security.carbondesignsystem.com/?path=/story/patterns-tearsheet--basic) component — specifically with Carbon checkbox inputs but it may or may not be isolated to checkboxes. Working fine on Firefox 83. Sandbox with instructions below.

- [Codesandbox](https://codesandbox.io/s/fervent-microservice-93b1o?file=/src/index.js)

#### Small teasheet
<insert small tearsheet use case>

### PR DESCRIPTION
**Pull request by clairek20**
…on 87

### Affected issues

- Resolves #863 

### Proposed changes

- removing overflow auto from both tearsheets seems to resolve the issue 

### Testing instructions

List of instructions for reviewer to test that proposed changes in this PR work properly

### CODE REVIEW

**Review by SimonFinney — APPROVED** [review]
LGTM! Thank you 🔥

**Review by ShayMurnin — APPROVED** [review]
Nice one @clairek20! LGTM.

**Comment by clairek20** [comment]
Hi @SimonFinney 
Could you merge this as i don't have the privileges to merge
Thanks in advance, Claire.

**Pull request merged**
