### PR TITLE
[WIP] feat(summary-card): add component and stories

### PR DESCRIPTION
**Pull request by jendowns**
## Proposed changes

- add `SummaryCard` component originally created in the private repo by @areddon

### CODE REVIEW

**Comment by jendowns** [comment]
@SimonFinney This PR doesn't include tests -- are you okay with a separate PR for that or would you prefer I add them to this one?

**Comment by jendowns** [comment]
@SimonFinney This is ready to review! Previous strangeness is resolved (I forgot to export the styles 😇 )

**Comment by jendowns** [comment]
@SimonFinney @j1mie @diego-codes when any of you have a chance, could you please take a look at this PR? 🙏 Thank you

**Comment by diego-codes** [comment]
Hi @jendowns, sorry for the delay on this. Before doing a code review I have an API improvement suggestion. Currently, the props for this component seem too complex and hard to understand sometimes.

Following Carbon's UI Shell, Data Table, and Composed Modal and our ComboBox components that allow consumers to pass in more complex data to a component, I'm wondering if this component would benefit from the same treatment.

My drive is to get components to have simpler props and more semantic flexibility. What if the API looked something more like this?

```jsx
<SummaryCard>
  <SummaryCardHeader 
    title="my title"
    status={<Tooltip renderIcon={MyIcon}>Tooltip content</Tooltip>}
   />
  <SummaryCardBody>
    Card content
  </SummaryCardBody>
  <SummaryCardFooter>
    <SummaryCardAction renderIcon={MyIcon} expandsDetails>Primary action</SummaryCardAction>
    <SummaryCardAction renderIcon={MyIcon}>Secondary action</SummaryCardAction>
    <SummaryCardAction renderIcon={MyIcon} iconOnly>Icon action</SummaryCardAction>
    <SummaryCardAction renderIcon={MyIcon} iconOnly disabled>Icon action</SummaryCardAction>
    {/* etc… */}
     <SummaryCardDetails>
      Expanded area content
    </SummaryCardDetails>
  </SummaryCardFooter>

</SummaryCard>
```

The API can be different from what I have, but I'm trying to put across the ability to compose the summary card.

**Comment by jendowns** [comment]
Thanks @diego-codes that makes sense & I like that API a lot 👍 I'll work on refactoring this & tag you again when it's ready to look at again.

**Comment by jendowns** [comment]
Because this component is undergoing such a comprehensive refactor, I'm going to close out this PR. I'll create an issue with the suggested API, and then add the appropriate milestone to that. 👍

**Pull request closed without merging**
