### PR TITLE
List module design documentation

### PR DESCRIPTION
**Pull request by rebecca-m-l**
## Design documentation

Includes:
- Anatomy
- Variants
- Grid placement

### CODE REVIEW

**Review by lily-peng — CHANGES_REQUESTED** [review]
It looks like we're getting an error when trying to preview: "No url found for submodule path 'ibm-security' in .gitmodules." 

I believe the "submodule" being referenced is an empty folder called ibm-security that was created in this commit. If it's not important, can we try removing it and seeing if the preview would work?

**Comment by rebecca-m-l** [comment]
> It looks like we're getting an error when trying to preview: "No url found for submodule path 'ibm-security' in .gitmodules."
> 
> I believe the "submodule" being referenced is an empty folder called ibm-security that was created in [this commit](https://github.com/carbon-design-system/ibm-security/pull/966/commits/244a90ed13c4743ff36ea780550924e8889650a5). If it's not important, can we try removing it and seeing if the preview would work?

Think this is resolved now and preview should work: https://deploy-preview-966--ibm-security.netlify.app/iframe?utm_source=github&utm_campaign=bot_dp

**Review by lily-peng — APPROVED** [review]

**Review by cameroncalder — APPROVED** [review]
LGTM 🙌

**Pull request merged**
