### PR TITLE
feat(deps): upgrade Carbon to `10.41`

### PR DESCRIPTION
**Pull request by SimonFinney**
### Proposed change

Upgrade Carbon packages to [`10.41`](https://github.com/carbon-design-system/carbon/releases/tag/v10.41.0), updating snapshots.

### CODE REVIEW

**Review by dbrugger — COMMENTED** [review]
thanks @SimonFinney. do these two changes depend on each other? if not we should split them into individual PRs as they seem to serve a different purpose.

**Review by thekevinboyle — COMMENTED** [review]
Nice one

**Pull request merged**
