### PR TITLE
docs(readme): update codesandbox link

### LINKED ISSUE #303: CodeSandbox - update version in demo to latest stable release
## Details

The CodeSandbox demo/template linked from the README (https://codesandbox.io/s/codesandbox-nmmqp) is on `1.1.0`, but we've had a number of stable releases since then.

We should update the CodeSandbox demo/template to the latest stable release 👍

### PR DESCRIPTION
**Pull request by jendowns**
## Affected issues

- Resolves #303 

## Proposed changes

- update CodeSandbox link to use instance with updated version of the library

### CODE REVIEW

**Comment by jendowns** [comment]
Thanks @SimonFinney I just added a `^` to the version. I wonder if using a `*` will match version `2.0.0`?

**Comment by SimonFinney** [comment]
That's a good point! I'm not entirely sure - I wonder if because `2.0.0` is currently a prerelease it may not pick that up? I think this is great for now!

**Pull request merged**
