### PR TITLE
fix(breadcrumb): force `visited` state override

### PR DESCRIPTION
**Pull request by SimonFinney**
## Proposed changes

- Force `visited` state for `Breadcrumbs` to remain as default state

### CODE REVIEW

**Comment by jendowns** [comment]
@SimonFinney Do you know where this feedback came from?

I seem to recall us going back and forth on this in the GHE repo. 🤔

**Comment by SimonFinney** [comment]
This issue came up this evening in discussion with @j1mie as part of their offering - it was something we had in place, but got lost with migration to `2.x`.

Full disclosure, I think it was me! 🤣I've posted a link on Slack to the original line.

**Pull request merged**
