### PR TITLE
feat(layout-modules): add comprehensive documentation

### PR DESCRIPTION
**Pull request by SimonFinney**
## Proposed change

Add comprehensive 'Layout modules' documentation to `dev` for review in advance of publishing

### CODE REVIEW

**Comment by SimonFinney** [comment]
@cameroncalder / @rebecca-m-l This is the sanity review on the layout modules documentation before we merge into `dev` - the deploy preview is available at https://deploy-preview-837--ibm-security.netlify.app

**Review by cameroncalder — CHANGES_REQUESTED** [review]
The UNSTABLE Layout Modules are anchoring down to the page to the ‘Overview section’ when pressing on the ‘Default’ links in the side menu

On ‘Variant’ & Interaction’ examples, can we default those to the ‘Canvas’ tab instead of ‘Docs’?


Update the following links:

**ActionBarModule**
icon button bar = /patterns-iconbuttonbar--default
narrow grid = https://react.carbondesignsystem.com/?path=/docs/grid--narrow


**ButtonClusterModule**
narrow grid = https://react.carbondesignsystem.com/?path=/docs/grid--narrow
spacing token = https://www.carbondesignsystem.com/guidelines/spacing/overview#spacing-scale


**CardModule**
grid = https://react.carbondesignsystem.com/?path=/docs/grid--narrow
render prop = https://reactjs.org/docs/render-props.html


**DescriptionListModule**
grid = https://react.carbondesignsystem.com/?path=/docs/grid--narrow
spacing token = https://www.carbondesignsystem.com/guidelines/spacing/overview#spacing-scale


**DescriptionModule**
paragraph elements = https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p
render prop = https://reactjs.org/docs/render-props.html
Anatomy section: Remove the link from ‘Learn more’ and add the link to ‘TitleBarModule’
grid = https://react.carbondesignsystem.com/?path=/docs/grid--narrow
spacing token = https://www.carbondesignsystem.com/guidelines/spacing/overview#spacing-scale


**ICAModule**
grid = https://react.carbondesignsystem.com/?path=/docs/grid--narrow
render prop = https://reactjs.org/docs/render-props.html

Anatomy section: `$layout-01` in 1 & 3 are not formatted correctly. Should be a code block


**TitleBarModule**
Variants: Remove the sentence ‘Learn more below.’
narrow grid = https://react.carbondesignsystem.com/?path=/docs/grid--narrow

**Review by cameroncalder — APPROVED** [review]
Looks good!

**Review by rebecca-m-l — APPROVED** [review]

**Pull request merged**
