### PR TITLE
260title bar label

### LINKED ISSUE #260: The automated release is failing 🚨
## :rotating_light: The automated release from the `2.x` branch failed. :rotating_light:

I recommend you give this issue a high priority, so other packages depending on you could benefit from your bug fixes and new features.

You can find below the list of errors reported by **semantic-release**. Each one of them has to be resolved in order to automatically publish your package. I’m sure you can resolve this 💪.

Errors are usually caused by a misconfiguration or an authentication problem. With each error reported below you will find explanation and guidance to help you to resolve it.

Once all the errors are resolved, **semantic-release** will release your package the next time you push a commit to the `2.x` branch. You can also manually restart the failed CI job that runs **semantic-release**.

If you are not sure how to resolve this, here is some links that can help you:
- [Usage documentation](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/README.md)
- [Frequently Asked Questions](https://github.com/semantic-release/semantic-release/blob/caribou/docs/support/FAQ.md)
- [Support channels](https://github.com/semantic-release/semantic-release#get-help)

If those don’t help, or if this issue is reporting something you think isn’t right, you can always ask the humans behind **[semantic-release](https://github.com/semantic-release/semantic-release/issues/new)**.

---

### The release `2.0.0` on branch `2.x` cannot be published as it is out of range.

Based on the releases published on other branches, only versions within the range `>=2.0.0 <1.10.1` can be published from branch `2.x`.

The following commits are responsible for the invalid release:
-  feat(panel): deprecate `Panel` in favor of `PanelV2` (#258) (441bdd8)
- Merge branch 'dev' into 2.x (6487fd9)
- chore(release): 1.10.2-prerelease.2 [skip ci] (1024be0)
- fix(data-table): fix theme tokens, reduce overrides (#252) (ccec2d6)
- chore(release): 1.10.2-prerelease.1 [skip ci] (a8b4ae0)
- fix(header): add hyphenated word break for popover title (#250) (495f531)
- refactor(error-page): add unused spacing values (#243) (2a9fb40)
- Merge branch 'dev' into 2.x (7339721)
- feat(grid): remove `css-gridish` (#238) (5f620cb)
- chore(release): create major branch, align release configuration (4d4dde9)

Those commits should be moved to a valid branch with [git merge](https://git-scm.com/docs/git-merge) or [git cherry-pick](https://git-scm.com/docs/git-cherry-pick) and removed from branch `2.x` with [git revert](https://git-scm.com/docs/git-revert) or [git reset](https://git-scm.com/docs/git-reset).

A valid branch could be `master`.

See the [workflow configuration documentation](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/workflow-configuration.md) for more details.

---

Good luck with your project ✨

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

### PR DESCRIPTION
**Pull request by thekevinboyle**
## Pull request - 
This creates a story for the TitleBarModule that adds a label to default and variant
### Affected issues

- Resolves #1040 

### Proposed changes

- 

### Testing instructions

-

### CODE REVIEW

**Review by cameroncalder — APPROVED** [review]
LGTM!

**Review by lily-peng — APPROVED** [review]
Nice work! LGTM

**Pull request merged**
