### PR TITLE
fix(status-indicator): update deprecated `InlineLoading` prop

### PR DESCRIPTION
**Pull request by SimonFinney**
## Affected issues

- Resolves partially #104

## Proposed changes

- Update deprecated `success` `InlineLoading` prop in `StatusIndicator` to `status`

### CODE REVIEW

**Comment by SimonFinney** [comment]
@jendowns Good point! I'll look at this in the morning

**Comment by SimonFinney** [comment]
@jendowns Absolutely! Since this table is generated from the available component prop types, it will continue to be displayed until Carbon has removed it from its definition - https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/InlineLoading/InlineLoading.js#L84

**Comment by jendowns** [comment]
@simonfinney Not necessarily — one solution is to just redefine the props inside the story & that would give the prop table accurate info

**Comment by SimonFinney** [comment]
@jendowns I'm not sure I follow, but that might help avoid confusion in cases like this! Could you provide an example and I can try it out?

**Comment by jendowns** [comment]
@SimonFinney I hear you, but I don't think it's necessarily something wrong with the component's props itself... I think there is something strange going on with something *WE* have done. I think it is related to the way we import the component (it is proxied) and the fact that we don't appear to have the right docgen info (again, because it is proxied?). 

But I think it would be a reasonable quickfix to redefine props in the docgen info in the story, like this. That way people have accurate information. It's a little copying & pasting for us, but honestly I think giving people accurate info is important in this case:

```
InlineLoading.__docgenInfo = {
  props: {
    className: {
      type: 'string',
      description: 'Specify a custom className to be applied to the container node',
    },
    success: {
      type: 'string',
      description: 'This prop has been deprecated in favor of `status`. Please use `status="finished" instead',
    },
    status: {
      type: 'oneOf \'default\' | \'field\' | \'large\' | \'small\'',
      description: 'Specify the loading status.',
    },
    description: {
      type: 'string',
      description: 'Specify the description of the inline loading text.'
    },
    iconDescription: {
      type: 'string',
      description: 'Specify the description for the inline loading text.'
    },
    onSuccess: {
      type: 'function',
      description: 'Provide an optional handler to be inovked when <InlineLoading> is successful',
    },
    successDelay: {
      type: 'number',
      description: 'Provide a delay for the `setTimeout` for success.',
      default: { value: 1500 }
    }
  },
};
```

(And what's nice about this route is you aren't actually messing with any proptypes they've set on the component... so the warning still shows up if you use `success`, for example)

**Comment by SimonFinney** [comment]
@jendowns Nice investigation - I hadn't realized this is an issue across all components we proxy from Carbon! I don't believe this was always the case?

Either way, we definitely need to create a separate issue for this, and find a larger solution instead of trying to stay in sync with ALL of Carbon's props and story information - it's not a good use of our time. 😱

Anyway, the change you initially requested is here - https://github.com/carbon-design-system/ibm-security/pull/106/files#diff-c41b47d28315f6b9c09af61d6e042d68R99

**Pull request merged**
