### PR TITLE
removes padding testing in styles

### LINKED ISSUE #1042: DescriptionList module type misalignment
The section title is not left-aligned with the descriptionList
https://ibm-security.carbondesignsystem.com/?path=/story/layout-modules-descriptionlistmodule--variant

image

### PR DESCRIPTION
**Pull request by thekevinboyle**
### Affected issues

- Resolves #1042 

### Proposed changes

- Overrides carbon's StructuredListCell `padding-left` . The TypeLayoutCell component is built with StructuredListCell but requires a different style.

### Testing instructions

-

### CODE REVIEW

**Review by cameroncalder — APPROVED** [review]
LGTM!

**Review by lily-peng — APPROVED** [review]
It looks like overriding the style in JS is something frequently done for stories in this repo, so this LGTM

**Pull request merged**
