### PR TITLE
feat: upgrade Carbon to 10.16.0 release, upgrade Filter to Downshift v5 API

### LINKED ISSUE #671: `TimePicker` padding
Screen Shot 2020-07-08 at 9 14 20 AM

Need to include padding for the time input

_Originally posted by @petervachon in https://github.com/carbon-design-system/ibm-security/pull/660#issuecomment-655555059_

### LINKED ISSUE #689: Upgrade to Carbon v10.16.0
### Description

Upgrade to the latest version of Carbon and manually verify that no issues were introduced:

- [ ]  https://github.com/carbon-design-system/carbon/releases/tag/v10.16.0

### PR DESCRIPTION
**Pull request by jendowns**
## Affected issues

Follow up to #678
Resolves #689 
Resolves #671

### Carbon

- upgrade Carbon packages to 10.16.0 release

### `Filter`

- upgrade to Downshift v5 API: https://github.com/downshift-js/downshift/blob/v5.2.1/README.md#usage

### `TagWallFilter`

- update `TagWallFilter` to render `Filter` contents via `body` prop of `TearsheetSmall` instead of `children` (note that `children` is deprecated in #678)

## Testing instructions

- ensure that `TagWallFilter` works as intended (due to Downshift upgrades)
- verify that components are stable after Carbon upgrade

### CODE REVIEW

**Comment by SimonFinney** [comment]
Thanks @jendowns - I interacted with the `TagWallFilter` in the deploy preview and there's a couple of things to note:

## Removing a tag results in the last added tag to be added to the input:

Remove

## Clearing the input throws the following error:

Clear

## General console error I couldn't reproduce in other environments:

Error

Thanks, and let me know your thoughts!

**Comment by jendowns** [comment]
This may be related Downshift updates in Carbon, so I will try to combine this with #689.

**Comment by jendowns** [comment]
@SimonFinney This is ready to review again

**Comment by SimonFinney** [comment]
Thanks - the Carbon upgrade looks great! The only thing I can see left is it looks like the `TagWallFilter` is still adding the tag label to the search input when a tag is added and subsequently removed:

TagWallFilter

**Comment by jendowns** [comment]
Hey heads up @SimonFinney I'll have time to return to this during the week. Also went ahead and put some of those tall screenshots in `<details>` elements so the PR is easier traverse. 👍

**Comment by jendowns** [comment]
So FYI, this PR looks great locally but I'm not sure why the filtering behaves differently in the deployed environment versus local development.

But given that you've opened #765, should I just close this out @SimonFinney?

**Comment by SimonFinney** [comment]
It'll be useful to retain the `Filter` work while the issue still exists - if you have the bandwidth to continue investigating, it's worth keeping the PR open, otherwise, we can keep the branch alive until there's time to revisit.

**Pull request closed without merging**
