### PR TITLE
fix: restructure individual styles

### LINKED ISSUE #44: Modularise component styles
## Context

- Make components, and their styles consumable on an individual basis
- Enables consumers to compile Sass if preferred to CSS
- Preview each component and its style in isolation of other styles to test partials (rather than importing `globals/index`, which has known performance issues)
- Debug performance issues 

## Components (tag yourself on component PRs you're working on)

- [x] Accordion @j1mie 
- [x] Breadcrumb - @SimonFinney  
- [x] Button - @SimonFinney 
- [x] Card - @SimonFinney 
- [x] Checkbox @j1mie 
- [x] Codesnippet @j1mie 
- [x] ComboButton - @SimonFinney 
- [x] ContentSwitcher @j1mie 
- [x] DataDecorator @SimonFinney
- [x] DataTable @SimonFinney 
- [x] DatePicker @SimonFinney 
- [x] DelimitedList - @SimonFinney 
- [x] Dropdown @j1mie 
- [x] ErrorPage - @SimonFinney 
- [x] ExternalLink - @SimonFinney 
- [x] FileUploader - @SimonFinney 
- [x] FilterPanel - @SimonFinney 
- [x] Form @j1mie 
- [x] Header - @SimonFinney 
- [x] ICA / ICASkeleton - @SimonFinney 
- [x] IconButton - @SimonFinney 
- [x] IconButtonBar @SimonFinney
- [x] InlineLoading @j1mie 
- [x] Link @j1mie 
- [x] Loading @SimonFinney 
- [x] Modal @j1mie 
- [x] MultiSelect @j1mie 
- [x] Nav - @SimonFinney 
- [x] NonEntitledSection - @SimonFinney
- [x] Notification - @SimonFinney
- [x] NumberInput / Skeleton @j1mie 
- [x] OverflowMenu
- [x] Pagination @j1mie 
- [x] Panel @j1mie 
- [x] PanelV2 - @SimonFinney
- [x] Pill - @SimonFinney
- [x] Portal @j1mie
- [x] ProgressIndicator / Skeleton - @SimonFinney
- [x] ProfileImage - @SimonFinney 
- [x] RadioButton
- [x] RadioButtonGroup - @SimonFinney
- [x] ScrollGradient - @SimonFinney
- [x] Search - @SimonFinney 
- [x] SearchBar - @SimonFinney 
- [x] Select @j1mie 
- [x] Shell - @SimonFinney 
- [x] SkeletonText - @SimonFinney 
- [x] Slider @j1mie 
- [x] Stacked notification - @SimonFinney
- [x] StatusIcon - @SimonFinney 
- [x] StatusIndicator - @SimonFinney
- [x] StepIndicator - @SimonFinney 
- [x] StringFormatter @SimonFinney 
- [x] StructuredList @j1mie 
- [x] Summary card @SimonFinney 
- [x] Tabs @j1mie 
- [x] Tag / InteractiveTag @j1mie 
- [x] TagWall @j1mie 
- [x] TagWallFilter @j1mie 
- [x] Tearsheet @j1mie 
- [x] TearsheetSmall @j1mie 
- [x] TextArea @j1mie 
- [x] TextInput @j1mie 
- [x] Tile @SimonFinney 
- [x] Timepicker @j1mie 
- [x] Toggle / ToggleSmall @SimonFinney 
- [x] Toolbar - @SimonFinney 
- [x] Tooltip - @SimonFinney 
- [x] Transition - @SimonFinney 
- [x] TypeLayout - @SimonFinney 
- [x] Wizard - @SimonFinney 

## Other

- [x] Revisit outstanding `TODO`s

### PR DESCRIPTION
**Pull request by SimonFinney**
## Affected issues

- Resolves #44

## Proposed changes

Restructure individual styles of each component.

### CODE REVIEW

**Comment by SimonFinney** [comment]
@j1mie Reviving this for next sprint as per memory issues that have been raised with Create React App integration and our Slack discussion last week - let's sync on an approach to cherrypick completed work into `dev`

**Comment by j1mie** [comment]
Sounds good @SimonFinney

**Comment by j1mie** [comment]
:shipit:

**Pull request merged**
