### PR TITLE
fix(header): inherit height to accommodate breadcrumb shadow

### PR DESCRIPTION
**Pull request by SimonFinney**
## Proposed change

Reintroducing height inheritance to accommodate breadcrumb shadow

### CODE REVIEW

**Comment by SimonFinney** [comment]
FYI @chrismichaelmurphy

**Comment by SimonFinney** [comment]
@jendowns Good catch!

**Comment by chrismichaelmurphy** [comment]
What is the status of this PR @SimonFinney and @jendowns

**Comment by jendowns** [comment]
Hey @chrismichaelmurphy, 

In terms of PR status, what you see with the PR updates here is accurate. After updates, a new review was requested yesterday. However, yesterday was a US holiday.

**Comment by chrismichaelmurphy** [comment]
Thanks @SimonFinney and @jendowns

**Pull request merged**
