### PR TITLE
feat(carbon): upgrade dependencies

### LINKED ISSUE #700: Focus trap issues within Web Components
## Bug - Focus trap functionality breaks when rendered within a web component

**Expected behavior -**

When a component that utilizes the FocusTrap is used within a web component the user will be able to interact with the elements rendered within the focus trap and only those elements. Tabbing should be locked so that the selected element cannot escape the trap either.

**Actual behavior -**

The focus trap blocks interactions altogether including clicks and accessibility clicks (space / enter key). The user must press the escape button which essentially remove these focus trap and then the element is interactable by the user. This removes the benefits of the focus trap, such as tabbing outside of the intended trap elements.

### PR DESCRIPTION
**Pull request by SimonFinney**
## Affected issue

Resolves #700 

## Proposed change

Upgrade Carbon dependencies and snapshots

## Testing instructions

Relevant release notes:

- https://github.com/carbon-design-system/carbon/releases/tag/v10.21.0
- https://github.com/carbon-design-system/carbon/releases/tag/v10.22.0
- https://github.com/carbon-design-system/carbon/releases/tag/v10.23.0

### CODE REVIEW

**Review by JennChao — APPROVED** [review]
Looks good to me with DE storybook. Thanks!

**Review by petervachon — APPROVED** [review]
LGTM 👍

**Pull request merged**
