### PR TITLE
chore: merge `dev` into `next`

### PR DESCRIPTION
**Pull request by SimonFinney**
## Proposed changes

- #

### CODE REVIEW

**Comment by jendowns** [comment]
@SimonFinney Is #585 (from June 3) the intended cut-off in this PR?

**Comment by SimonFinney** [comment]
@jendowns I don't fully understand - would you mind elaborating?

**Comment by jendowns** [comment]
@SimonFinney For the collection of commits included in this PR, it is intentional that the most recent one is #585?

**Comment by SimonFinney** [comment]
Oh! You're correct - we'll require another merge from `dev` in the future after this PR 😭  The changeset should be smaller though 🤞

**Pull request merged**
