### PR TITLE
fix(nav-item): remove active state for external links

### LINKED ISSUE #473: Side Navbar links don't accurately represent current active state
## Bug - 

**Expected behavior -**

Should see only one state in blue

**Actual behavior -**

Seeing two states in blue

### Steps for reproducing

[CodeSandbox](https://codesandbox.io/s/)

1. Click the support nav icon.
2. Click on a link.
3. Click on another link, under a different header.
4. Notice the highlight staying on.

#### 

#### 

#### 

### Affected browsers

[What's my browser?](http://www.whatsmyua.com) and [browserl.ist supported browsers](http://browserl.ist/?q=%3E+1%25%2C+not+IE+11)

- [ ]  / 
- [ ]  / 
- [ ]  / 

### Optional information

**Version -**

### PR DESCRIPTION
**Pull request by SimonFinney**
## Affected issues

Resolves #473 

## Proposed change

Remove `NavList` active state if the link is external

### CODE REVIEW

**Comment by SimonFinney** [comment]
FYI @chrismichaelmurphy

**Comment by chrismichaelmurphy** [comment]
Thanks @SimonFinney

**Pull request merged**
