### PR TITLE
feat(layout-modules): add foundation, action bar module

### PR DESCRIPTION
**Pull request by SimonFinney**
## Proposed change

- Scaffold folder structure for layout modules
- Add `LayoutModule` foundational component to support individual layout module construction
- Add `ActionBar` layout module and sub-components and Storybook stories
- Add Storybook decorator to support responsive behaviour using Carbon breakpoints

### CODE REVIEW

**Comment by SimonFinney** [comment]
@Deriohig As per our Slack conversation, I'm marking this as ready - let me know if you have any questions!

**Review by Deriohig — APPROVED** [review]
Looks good. 👍 interesting aproach

**Pull request merged**
