### PR TITLE
docs(categories): reorganise categories

### PR DESCRIPTION
**Pull request by SimonFinney**
### Proposed change

Further distinguish between Security-specific and proxied Carbon components

### CODE REVIEW

**Comment by SimonFinney** [comment]
@cameroncalder what are your thoughts on something like this? I'm hoping to further distinguish between the mental model of Carbon proxied versus Security-specific

**Comment by cameroncalder** [comment]
I like this. The separation might prove to be valuable during the merge or migration so we can be more deliberate about the state of Security-owned components

**Review by cameroncalder — APPROVED** [review]
LGTM!

**Pull request merged**
