### PR TITLE
fix(header): prevent header popover's width from spanning browser window

### PR DESCRIPTION
**Pull request by sbutler2901**

### CODE REVIEW

**Comment by sbutler2901** [comment]
@jendowns thanks for the feedback, I didn't realize Addons was taking a mobile first strategy here! I was replicating what we have done in CLX. I'll see if I can improve this PR based on your suggestions.

**Comment by SimonFinney** [comment]
@cameroncalder / @petervachon would ye have any thoughts in how the header popover should behave at medium breakpoints?

**Comment by petervachon** [comment]
For the popover, I would keep the same behavior on medium and large breakpoints and only go full-width for the small breakpoint.

**Pull request merged**
